### ISSUE TITLE
Puedes usar Flake8 para darle un mejor formato al codigo

### ISSUE THREAD

**Issue by mvargasevans** [Fvalenci2020/PNP#4]
Aca:
https://pypi.org/project/flake8/

Si activas el Lynter (usas Visual Studio Code?), te va a marcar los errores de formato.
Con esto tu codigo va a ser mas ordenado y facil de revisar en el futuro.

**Comment by Fvalenci2020** [comment]
Gracias Manu! estamos vuelto locos pq nos vamos a mudar, así que no he tenido tiempo de investigar más sobre github, aunque ha sido de gran ayuda. nos mareamos en el uso de branch eso si, pero bueno, al final funcionó.
